### ISSUE TITLE
Problem with Roles, please help!

### ISSUE THREAD

**Issue by alcastronava** [aspnet/Docs#8683]
I follow this article to create my own custom user data, 
then I follow this other to add Admin user and create and asign Admin Role

https://social.technet.microsoft.com/wiki/contents/articles/51333.asp-net-core-2-0-getting-started-with-identity-and-role-management.aspx

but I can not add roles using the UserManager and RoleManager
I have this Exception: NotSupportedException: Store does not implement IUserRoleStore&lt;TUser&gt;
When try to call "UserManager.AddToRoleAsync" 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by alcastronava** [comment]
Fixed! Thanks anyway.
I must delete the autogenerate IdentityHostingStartup.Configure method

**Comment by Rick-Anderson** [comment]
@alcastronava 	 glad you got it fixed.

**Comment by alcastronava** [comment]
Welcome!

**Comment by msstop** [comment]
well, it didnt fix my issue. Everyday I am questioning my decision to choose ms stack!!!!

**Comment by msstop** [comment]
Everything is so branched out. Either you can not follow their guide since it is fixed to a set of versions that is almost impossible to provide or when you follow it, it does not work. Then you are old oh your bla bla version is bla bla!!!!!

**Comment by ZyuHoiMing** [comment]
Thanks for the idea you provided, which help me a lot in using asp.net identity in asp.net 2.2
In **asp.net 2.2**, when you need to use the userManager.addToRole(user,role) method to role the role based identity. Can follow the guidance in here (which is the guidance actually in asp.net 2.1):
https://docs.microsoft.com/zh-cn/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2

**It is actually same and what different is :**
when you meet this :
##Add Role services to Identity
remember to replace the row

`services.AddDefaultIdentity<IdentityUser>().AddEntityFrameworkStores<ApplicationDbContext>();`

with

`services.AddDefaultIdentity<IdentityUser>().AddRoles<IdentityRole>().AddEntityFrameworkStores<ApplicationDbContext>();`

in IdentityHostingStartup.Configure method (the file can't be deleted in asp.net 2.2)

I have made a duplicated declaration in AddDefaultIdentity (I add it follow the guidance), which brings me a exception : "Store does not implement IUserRoleStore<TUser>"
